# Site settings
author: Kayvan Vakili
title: Kayvan Vakili
header-img: img/home-bg.png
email: kvakili813@gmail.com
copyright_name: Kayvan Vakili
description: > # this means to ignore newlines until "baseurl:"
  Coding to bridge gaps.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kvakili813

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
